### ISSUE TITLE
Gulp tasks don't exit when gulp-libsquoosh is included

### ISSUE THREAD

**Issue by pavlo-tk** [pekeq/gulp-libsquoosh#8] opened 2021-09-13 22:05 UTC
Hi,

I've spent a few hours trying to figure out why my Gulp tasks don't exit after they've been finished and finally I pin-pointed the issue to the `gulp-libsquoosh` library.

So, the issue is that none of Gulp tasks exit after being finished if `gulp-libsquoosh` is included in the `gulpfile.js`. You don't have to use it in the task, just include, and that's enough to break all other tasks. It's easy to reproduce the issue with this minimal `gulpfile.js`:

```javascript
const { src } = require('gulp');
const squoosh = require('gulp-libsquoosh');

function defaultTask() {
    return src('.')
}

exports.default = defaultTask;
```

Then just run the default task in a console: `gulp`.
After running the task you'll see that it never exits:

```
pavlo@DESKTOP-O2A9C8P:~$ gulp
[14:59:25] Using gulpfile ~/gulpfile.js
[14:59:25] Starting 'default'...
[14:59:25] Finished 'default' after 30 ms
|
```

The expected outcome is that the task finishes and exits back to the console.
As soon as I comment out the `gulp-libsquoosh` include, the task exits fine. The same will happen with all other tasks in the `gulpfile.js`.

**Versions I'm using:**
`gulp`: 4.0.2
`gulp-libsquoosh`: 1.0.10

**Comment by pekeq** [comment] 2021-09-14 04:09
@pavlo-tk Thank you for your report.

I reproduced this problem.
This problem seems to occur when not calling imagePool.close() after calling new ImagePool().

```javascript
const libSquoosh = require('@squoosh/lib');
const imagePool = new libSquoosh.ImagePool();
```

```shell
$ node case.js 
(never exit)
^C
```

gulp-libsquoosh doesn't close imagePool since repeating new/close ImagePool will cause memory leak.

I'll investigate more detail.

**Comment by pavlo-tk** [comment] 2021-09-14 23:08
No problem @pekeq.
I had a suspicion that the pool is not closed, while it's advised to (https://github.com/GoogleChromeLabs/squoosh/tree/dev/libsquoosh#closing-the-imagepool), but didn't know about a memory leak.

Please investigate — you know this stuff much better than me.
Thank you for a quick reply.

**Comment by pavlo-tk** [comment] 2021-09-15 18:50
Okay, forgive me, I was too fast with the conclusion.
While all tasks that don't use `gulp-libsquoosh` are exiting fine now, the ones that do aren't exiting for, I suspect, the same reason.

So, basically, this one will not exit:
```javasvcript
function images() {
    return src('.')
        .pipe(squoosh({
            webp: {}
        }))
        .pipe(dest('./dist'))
}
```

**Comment by pekeq** [comment] 2021-09-16 08:56
@pavlo-tk 
Yes, I am facing same problem.
I opened an issue on libsquoosh project and considering workaround to prevent this issue.

**Comment by pekeq** [comment] 2021-09-16 12:16
gulp-libsquoosh reuse libSquoosh ImagePool instance to prevent "wasm memory error" issue.
This issue caused because of not closing ImagePool instance.

I asked that closing ImagePool is needed by spec on libSquoosh project.
libsquoosh author (@surma) answered "Yes, its not a bug".
https://github.com/GoogleChromeLabs/squoosh/issues/1156

So I'll write following modification:
* close ImagePool instance
* in libSquoosh v0.4.0, closing ImagePool instance will occur "wasm memory error", so I rollback libSquoosh to v0.3.1

**Comment by pekeq** [comment] 2021-09-16 12:29
@pavlo-tk Thanks for sticking with me on this issue.
I have published new version (1.0.12).  I am happy if you have time to try this.

Thanks,

**Comment by pavlo-tk** [comment] 2021-09-16 23:07
No problem, thank you for investigating.

Before I try the new version, may I ask what are the downsides of downgrading the `libSquoosh` library from 0.4.0 to 0.3.1 and whether the compromise of having the newer version (0.4.0) and Cmd + Cing would have been acceptable outcome instead?

**Comment by pekeq** [comment] 2021-09-17 14:03
> what are the downsides of downgrading the libSquoosh library from 0.4.0 to 0.3.1

There are many improvements from 0.3.1 to 0.4.0. (ex. compression module upgrade, image file treatment bug fixes, etc.)
Downgrade means to drop these improvements.
(So I tried to avoid downgrade, but downgrade is necessary for stability.)

> and whether the compromise of having the newer version (0.4.0) and Cmd + Cing would have been acceptable outcome instead?

You can use newer libSquoosh with gulp-libsquoosh using following steps.

```
$ npm i gulp-libsquoosh
$ npm i @squoosh/lib@latest
```

There are some known issues:

* Sometimes gulp doesn't terminate.  You can terminate with Ctrl-C
* Sometimes you get 'wasm memory error'.  I have not been able to identify the conditions to reproduce it, but this error sometimes occurs.  (If you have caught this error, you can try upgrade nodejs version)

**Comment by pekeq** [comment] 2021-09-21 08:45
Closing this issue.
If you have any other (or similar) issue, please create new issue
Thanks for staying to solve this issue.

**Closed by pekeq** 2021-09-21 08:45 UTC

**Comment by pavlo-tk** [comment] 2021-09-21 16:01
Thank you!
